spring.application.name=backend
server.port=8081

# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/codelens_db
spring.datasource.username=postgres
spring.datasource.password=Rushabh@123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Docker Compose - disabled, we manage it manually
spring.docker.compose.enabled=false
codelens.clone.path=./temp-repos